const header=document.querySelector('[data-header]')||document.querySelector('.site-header');
let menuToggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.site-nav');
if(nav&&!nav.id)nav.id='site-nav';
if(header&&nav&&!menuToggle){menuToggle=document.createElement('button');menuToggle.className='menu-toggle';menuToggle.type='button';menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-controls',nav.id||'site-nav');menuToggle.setAttribute('aria-label','Open menu');menuToggle.innerHTML='<span></span><span></span>';header.querySelector('.header-inner')?.insertBefore(menuToggle,nav);}
const serviceTabs=[...document.querySelectorAll('.service-tab')];
const serviceImage=document.querySelector('[data-service-image]');
const serviceEyebrow=document.querySelector('[data-service-eyebrow]');
const serviceTitle=document.querySelector('[data-service-title]');
const serviceBody=document.querySelector('[data-service-body]');
const serviceList=document.querySelector('[data-service-list]');
const serviceCta=document.querySelector('[data-service-cta]');
const formEndpoint='';
const services={
 managed:{label:'Managed services',title:'Keep it running.',body:'24×7 monitoring and support for reliable network performance.',items:['Network performance monitoring','Fault detection and alarms','Performance reporting','SLA management'],cta:'Learn more about managed services',page:'services/managed-services.html',image:'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&q=85',alt:'Network operations equipment'},
 engineering:{label:'Engineering services',title:'Get the site moving.',body:'From site identification to a ready telecom site.',items:['Site identification','Stakeholder negotiation','Permitting support','Land, access and utility preparation'],cta:'Learn more about engineering services',page:'services/engineering-services.html',image:'https://images.unsplash.com/photo-1681735342773-d452708e87e7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGVsZWNvbSUyMGVuZ2luZWVyaW5nfGVufDB8fDB8fHww',alt:'Telecom infrastructure in a landscape'},
 energy:{label:'Renewable energy solutions',title:'Make power work harder.',body:'Hybrid energy systems for dependable remote-site power.',items:['Lithium-ion batteries','Hybrid wind and solar','Off-grid backup power','Lower operating costs'],cta:'Learn more about energy solutions',page:'services/renewable-energy.html',image:'https://plus.unsplash.com/premium_photo-1679917152396-4b18accacb9d?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',alt:'Energy infrastructure in a remote landscape'},
 repair:{label:'Repair & return services',title:'Get equipment back.',body:'Repair and testing that returns critical assets to service.',items:['Lithium-ion battery repair','Rectifier module repair','DG module support','Return-to-service testing'],cta:'Learn more about repair services',page:'services/repair-return.html',image:'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1000&q=85',alt:'Technician working with industrial equipment'},
 iot:{label:'IoT solutions',title:'See what’s happening.',body:'Real-time monitoring for clearer operational decisions.',items:['Operational insights','Data-driven decisions','Real-time visibility','Energy monitoring and control'],cta:'Learn more about IoT solutions',page:'services/iot-solutions.html',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=85',alt:'Connected technology circuit board'},
 people:{label:'BPO / HR / payroll',title:'Put people in place.',body:'HR, payroll and recruitment support for telecom teams.',items:['HR operations support','Payroll management','Administration support','Recruitment services'],cta:'Learn more about people services',page:'services/bpo-hr-payroll.html',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85',alt:'Team collaborating in a meeting'}
};
const servicePageHero=document.querySelector('.inner-hero');const currentService=Object.values(services).find(data=>location.pathname.endsWith(data.page.split('/').pop()));if(servicePageHero&&currentService&&location.pathname.includes('/services/')){const imageWrap=document.createElement('div');imageWrap.className='service-page-visual';imageWrap.innerHTML=`<img src="${currentService.image}" alt="${currentService.alt}" loading="eager">`;servicePageHero.querySelector('.container')?.append(imageWrap)}
const setService=key=>{const data=services[key];if(!data||!serviceImage)return;serviceTabs.forEach(t=>{const active=t.dataset.service===key;t.classList.toggle('is-active',active);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});serviceImage.style.opacity='0';window.setTimeout(()=>{serviceImage.src=data.image;serviceImage.alt=data.alt;serviceEyebrow.textContent=data.label;serviceTitle.textContent=data.title;serviceBody.textContent=data.body;serviceList.innerHTML=data.items.map(item=>`<li>${item}</li>`).join('');serviceCta.href=data.page;serviceCta.firstChild.textContent=data.cta+' '; document.querySelector('#service-counter').textContent = '0' + (Object.keys(services).indexOf(key) + 1) + ' / 06';document.querySelector('#service-panel')?.setAttribute('aria-labelledby',`service-${key}`);serviceImage.style.opacity='1';},150)};
const closeMenu=()=>{if(!header?.classList.contains('menu-open'))return;header.classList.remove('menu-open');menuToggle?.setAttribute('aria-expanded','false');menuToggle?.setAttribute('aria-label','Open menu');menuToggle?.focus();};
const updateHeader=()=>header?.classList.toggle('scrolled',window.scrollY>24);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
menuToggle?.addEventListener('click',()=>{const open=header.classList.toggle('menu-open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close menu':'Open menu');if(open)nav?.querySelector('a')?.focus();});
nav?.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
document.addEventListener('click',event=>{if(header?.classList.contains('menu-open')&&!header.contains(event.target))closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&header?.classList.contains('menu-open'))closeMenu();if(!header?.classList.contains('menu-open')||event.key!=='Tab')return;const focusable=[menuToggle,...nav.querySelectorAll('a')].filter(Boolean);const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
serviceTabs.forEach((tab,index)=>{tab.addEventListener('mouseenter',()=>setService(tab.dataset.service));tab.addEventListener('click',()=>{const data=services[tab.dataset.service];if(data?.page)window.location.href=data.page});tab.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%serviceTabs.length;else if(event.key==='ArrowLeft')next=(index-1+serviceTabs.length)%serviceTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=serviceTabs.length-1;else return;event.preventDefault();serviceTabs[next].focus();setService(serviceTabs[next].dataset.service);});});
document.querySelectorAll('[data-filter]').forEach(card=>card.addEventListener('click',()=>{const match={network:'managed',site:'engineering',power:'energy',equipment:'repair'}[card.dataset.filter];if(match)setService(match)}));
document.querySelectorAll('[data-jump-service]').forEach(link=>link.addEventListener('click',()=>setService(link.dataset.jumpService)));
document.querySelectorAll('[data-fallback-image]').forEach(image=>image.addEventListener('error',()=>{image.removeAttribute('src');image.classList.add('image-failed')}));
document.querySelectorAll('img').forEach(image=>image.addEventListener('error',()=>{image.removeAttribute('src');image.classList.add('image-failed')}));
const handleForm=(form,kind)=>{const status=form.querySelector('[data-form-status]');form.addEventListener('submit',async event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();status.textContent='Please check the highlighted fields.';status.className='form-status is-error';return}const file=form.querySelector('[data-cv-input]')?.files?.[0];if(file&&(file.size>5*1024*1024||!/^application\/(pdf|msword|vnd.openxmlformats-officedocument.wordprocessingml.document)$/.test(file.type))){status.textContent='Please choose a PDF, DOC or DOCX file smaller than 5 MB.';status.className='form-status is-error';return}if(!formEndpoint){status.innerHTML=kind==='careers'?'Your application is prepared locally, but secure CV submission is not connected yet. Please email your CV to <a href="mailto:HR@frontiertowers.com.pk">HR@frontiertowers.com.pk</a>.':'Online enquiry submission is not connected yet. Please email <a href="mailto:info@frontiertowers.com.pk">info@frontiertowers.com.pk</a> or call +92 311 1103181.';status.className='form-status is-note';return}const button=form.querySelector('button[type="submit"]');button.disabled=true;button.setAttribute('aria-busy','true');status.textContent='Sending…';try{const response=await fetch(formEndpoint,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Request failed');status.textContent='Thanks — your submission has been sent.';status.className='form-status is-success';form.reset()}catch(error){status.textContent='We could not send this submission. Please use the email address shown here.';status.className='form-status is-error'}finally{button.disabled=false;button.removeAttribute('aria-busy')}})};
document.querySelectorAll('[data-form-status]').forEach((status,index)=>{if(!status.id)status.id=`form-status-${index+1}`;status.closest('form')?.querySelectorAll('input,select,textarea').forEach(field=>field.setAttribute('aria-describedby',status.id));});document.querySelectorAll('[data-contact-form]').forEach(form=>handleForm(form,'contact'));document.querySelectorAll('[data-careers-form]').forEach(form=>handleForm(form,'careers'));
const observer=new IntersectionObserver((entries,obs)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');obs.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
const marketMarquee=document.querySelector('[data-market-marquee]');if(marketMarquee){const marketTrack=marketMarquee.querySelector('.market-track');const marketClone=marketTrack.cloneNode(true);marketClone.setAttribute('aria-hidden','true');marketClone.querySelectorAll('img').forEach(image=>image.addEventListener('error',()=>{image.removeAttribute('src');image.classList.add('image-failed')}));marketTrack.after(marketClone)}
